name: Mirror to GitLab via SSH

on:
  push:
    branches:
      - '**' # trigger on all branches

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # important to push all branches/tags

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.GITLAB_ORGANIZATION_SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan gitlab.kuleuven.be >> ~/.ssh/known_hosts

      - name: Push to GitLab
        run: |
          git config --global user.email "ci@example.com"
          git config --global user.name "GitHub CI Mirror"
          git remote add gitlab git@gitlab.kuleuven.be:rob-expressiongraphs/ros2/crospi_github_mirror/template_driver_crospi.git
          git push --all gitlab
          git push --tags gitlab
